runtime: python37

env_variables:
  CLOUD_SQL_USERNAME: 'root'
  CLOUD_SQL_PASSWORD: 'x6iBKeMeDPyOuj9k'
  CLOUD_SQL_DATABASE_NAME: 'booking_project'
  CLOUD_SQL_CONNECTION_NAME: 'bookingapp-288110:us-east1:bookingdb'
  JWT_SECRET_KEY: 't1NP63m4wnBg6nyHYKfmc2TpCOGI4nss'
  CLOUD_STORAGE_BUCKET: 'api-images-hotels'